[features]
seeds = false
[programs.localnet]
smart_contract = "EvwRqqGwNSnnwv8p67TL1n4y1YgiYDdgNzh8ntvDQdkw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/app/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
